_installSymLink $HOME/.config/alacritty $HOME/my-hypr/alacritty $HOME/.config
_installSymLink $HOME/.config/dunst $HOME/my-hypr/dunst $HOME/.config
_installSymLink $HOME/.config/hypr $HOME/my-hypr/hypr $HOME/.config
_installSymLink $HOME/.config/htop $HOME/my-hypr/htop $HOME/.config
_installSymLink $HOME/.config/rofi $HOME/my-hypr/rofi $HOME/.config
_installSymLink $HOME/.config/swappy $HOME/my-hypr/swappy $HOME/.config
_installSymLink $HOME/.config/waybar $HOME/my-hypr/waybar $HOME/.config
_installSymLink $HOME/.config/wlogout $HOME/my-hypr/wlogout $HOME/.config
_installSymLink $HOME/.config/starship.toml $HOME/my-hypr/starship/starship.toml $HOME/.config
_installSymLink $HOME/.config/gtk-3.0 $HOME/my-hypr/gtk/gtk-3.0 $HOME/.config
_installSymLink $HOME/.config/gtk-4.0 $HOME/my-hypr/gtk/gtk-4.0 $HOME/.config
_installSymLink $HOME/.config/xsettingsd $HOME/my-hypr/gtk/xsettingsd $HOME/.config
_installSymLink $HOME/.gtkrc-2.0 $HOME/my-hypr/gtk/.gtkrc-2.0 $HOME
_installSymLink $HOME/.Xresources $HOME/my-hypr/gtk/.Xresources $HOME
_installSymLink $HOME/.zshrc $HOME/my-hypr/.zshrc $HOME
