# packages that comes with a .Desktop entry or a GUI
packagesPacman=(
    "alacritty"
    "bitwarden"
    "bleachbit"
    "btop"
    "chromium"
    "fcitx5-im"
    "fcitx5-chewing"
    "gcolor3"
    "htop"
    "libreoffice-fresh"
    "marker"
    "mpv"
    "pdfarranger"
    "ranger"
    "spotify-launcher"
    "telegram-desktop"
    "texmaker"
    "vlc"
)

packagesYay=(
    "btrfs-assistant"
    "cpu-x"
    "etcher-bin"
    "hardinfo2"
    "octopi"
    "wl-color-picker"
    "zotero"
)
